// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmvXUyxzPPdVOIgs3eI5eJNw-pV3r7VW0',
    appId: '1:650905587926:web:d5a928169784e866edb977',
    messagingSenderId: '650905587926',
    projectId: 'arkitektagattin',
    authDomain: 'arkitektagattin.firebaseapp.com',
    storageBucket: 'arkitektagattin.appspot.com',
    measurementId: 'G-D0444JDFHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4JxJmajlYVadG9uR6OjlfUazLZItWqAY',
    appId: '1:650905587926:android:bbb4dcadec5a2f2eedb977',
    messagingSenderId: '650905587926',
    projectId: 'arkitektagattin',
    storageBucket: 'arkitektagattin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdx1oZ6zKhYE3_jLFiWYbNYmIA-oD9Wkc',
    appId: '1:650905587926:ios:0647960a9368b992edb977',
    messagingSenderId: '650905587926',
    projectId: 'arkitektagattin',
    storageBucket: 'arkitektagattin.appspot.com',
    iosClientId: '650905587926-vmueu3h1q080jm0e6phs94ioc3p24m4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.arch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdx1oZ6zKhYE3_jLFiWYbNYmIA-oD9Wkc',
    appId: '1:650905587926:ios:16dbf9fa449f7e2dedb977',
    messagingSenderId: '650905587926',
    projectId: 'arkitektagattin',
    storageBucket: 'arkitektagattin.appspot.com',
    iosClientId: '650905587926-0uo8pr0i5jj8aipfcl43ariu2b429lii.apps.googleusercontent.com',
    iosBundleId: 'com.example.arch.RunnerTests',
  );
}
